#!/usr/bin/env python3
"""Generate the portable ComplexMeshLib/ComplexImageLib declaration table.

Input is the historical Windows ResourceManager.cpp on stdin.  The checked-in
output is deliberately mechanical so every legacy call, flag and duplicate is
reviewable without needing the historical Git object at build time.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


SOURCE_COMMIT = "eff933868c1fbdfd266738a403fac80084f2b51e"
SOURCE_PATH = "prog/Rock3dGame/source/game/ResourceManager.cpp"
EXPECTED_MESH_CALLS = 324
EXPECTED_IMAGE_CALLS = 490


def source_path(value: str) -> str:
    return "Data/" + value.replace("\\\\", "/")


def boolean(value: str) -> str:
    if value not in {"true", "false"}:
        raise ValueError(f"unsupported boolean expression: {value}")
    return value


def tag(value: str, kind: str) -> tuple[int, bool, bool]:
    if value == "-1":
        return -1, False, False
    match = re.fullmatch(
        rf"Planet::wtWorld([1-6])\s*\|\s*{kind}Lib::cTag"
        rf"({'LoadData|InitIVB' if kind == 'Mesh' else 'InitTex2d|InitCubeTex'})",
        value,
    )
    if match is None:
        raise ValueError(f"unsupported {kind} tag expression: {value}")
    action = match.group(2)
    first = action in {"LoadData", "InitTex2d"}
    second = action in {"InitIVB", "InitCubeTex"}
    return int(match.group(1)) - 1, first, second


def calls(text: str, kind: str) -> list[tuple[int, str, list[str]]]:
    pattern = re.compile(
        rf'^\s*Load{kind}\("([^"]+)"(?:,\s*(.*?))?\);\s*$'
    )
    result: list[tuple[int, str, list[str]]] = []
    for line_number, line in enumerate(text.splitlines(), 1):
        if line.lstrip().startswith("//"):
            continue
        match = pattern.match(line)
        if match is None:
            continue
        arguments = [
            item.strip()
            for item in (match.group(2) or "").split(",")
            if item.strip()
        ]
        result.append((line_number, source_path(match.group(1)), arguments))
    return result


def mesh_line(line_number: int, path: str, arguments: list[str]) -> str:
    if len(arguments) > 4:
        raise ValueError(f"line {line_number}: too many LoadMesh arguments")
    values = arguments + ["false", "false", "false", "-1"][len(arguments):]
    build_tbn, load_data, initialize, tag_value = values
    world, tagged_load, tagged_initialize = tag(tag_value, "Mesh")
    return (
        f'    {{"{path}", {boolean(build_tbn)}, {boolean(load_data)}, '
        f'{boolean(initialize)}, {world}, {str(tagged_load).lower()}, '
        f'{str(tagged_initialize).lower()}}}, // source:{line_number}'
    )


def image_line(line_number: int, path: str, arguments: list[str]) -> str:
    if len(arguments) > 6:
        raise ValueError(f"line {line_number}: too many LoadImage arguments")
    defaults = ["1", "false", "false", "-1", "false"]
    values = arguments + defaults[len(arguments):]
    level, initialize_2d, initialize_cube, tag_value, gui = values
    if level == "cGenMipLevel":
        level = "0"
    if not level.isdecimal():
        raise ValueError(f"line {line_number}: unsupported level count {level}")
    world, tagged_2d, tagged_cube = tag(tag_value, "Image")
    return (
        f'    {{"{path}", {level}U, {boolean(initialize_2d)}, '
        f'{boolean(initialize_cube)}, {world}, {str(tagged_2d).lower()}, '
        f'{str(tagged_cube).lower()}, {boolean(gui)}}}, // source:{line_number}'
    )


def generate(text: str) -> str:
    meshes = calls(text, "Mesh")
    images = calls(text, "Image")
    if len(meshes) != EXPECTED_MESH_CALLS:
        raise ValueError(
            f"expected {EXPECTED_MESH_CALLS} LoadMesh calls, got {len(meshes)}"
        )
    if len(images) != EXPECTED_IMAGE_CALLS:
        raise ValueError(
            f"expected {EXPECTED_IMAGE_CALLS} LoadImage calls, got {len(images)}"
        )
    mesh_rows = "\n".join(mesh_line(*entry) for entry in meshes)
    image_rows = "\n".join(image_line(*entry) for entry in images)
    return f"""// Generated by tools/generate_original_resource_catalog.py.
// Provenance: {SOURCE_COMMIT}:{SOURCE_PATH}
// Do not hand-edit; repeated source declarations are intentionally retained.
const std::vector<MeshResourceDeclaration> sourceMeshResourceCatalog{{
{mesh_rows}
}};

const std::vector<ImageResourceDeclaration> sourceImageResourceCatalog{{
{image_rows}
}};
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    arguments = parser.parse_args()
    output = generate(sys.stdin.read())
    arguments.output.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
