macro(add_dir DIRS FILE_GROUP)
  foreach(dir ${DIRS})
    message("adding ${dir} to ${FILE_GROUP}")
#    include_directories(${dir})
    file( GLOB ${dir}_SOURCE_ADD ${dir}/*.cpp ${dir}/*.cxx ${dir}/*.c )
    list( APPEND ${FILE_GROUP}_SOURCE ${${dir}_SOURCE_ADD} )
    file( GLOB ${dir}_INLINE_ADD ${dir}/*.inl )
    list( APPEND ${FILE_GROUP}_INLINE ${${dir}_INLINE_ADD} )
    file( GLOB ${dir}_HEADER_ADD ${dir}/*.h ${dir}/*.hpp )
    list( APPEND ${FILE_GROUP}_HEADER ${${dir}_HEADER_ADD} )
  endforeach()
endmacro()
