name: CI

on: [push, pull_request]

jobs:
  win:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        configuration: [msvc-x86-debug, msvc-x86-release]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Windows libs
      shell: cmd
      run: |
        curl -LJO https://github.com/q4a/rrr3d/releases/download/1.3.1-dev2/extern.7z
        7z x extern.7z
        dir
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Configure with CMakeSettings.json and build
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        cmakeSettingsJsonPath: '${{ github.workspace }}/CMakeSettings.json'
        useVcpkgToolchainFile: false
        buildDirectory: '${{ github.workspace }}/build'
        configurationRegexFilter: '${{ matrix.configuration }}'
